# render.yaml (Super Simple Version)
services:
  - type: web
    name: netflix-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"

  - type: web
    name: telegram-bot
    env: python
    rootDir: bot
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bot:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.9
      - key: TELEGRAM_BOT_TOKEN
        sync: false
